networks:
  redisn:
    driver: bridge

services:
  map-scraper:
    build: ./map-scraper
    container_name: map_scraper_waze
    networks:
      - redisn
    volumes:
      - ./map-scraper:/app

  mongo:
    build: ./bdd
    container_name: mongo_waze
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    networks:
      - redisn
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo-express:
    image: mongo-express
    container_name: mongo_express_waze
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin123
      - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
      - redisn
    depends_on:
      - mongo

  mongo-exporter:
    build: ./mongo-exporter
    container_name: mongo_exporter
    networks:
      - redisn
    depends_on:
      - mongo
    volumes:
      - ./data:/data
    environment:
      - MONGO_HOST=mongo
      - MONGO_DB=waze_db
      - MONGO_COLLECTION=alertas
      - MONGO_USER=admin
      - MONGO_PASS=admin123

  hadoop-pig:
    build: ./hadoop-pig
    container_name: hadoop_pig_waze
    networks:
      - redisn
    volumes:
      - ./data:/data
      - ./hadoop-pig/scripts:/scripts
    stdin_open: true
    tty: true
    depends_on:
      - mongo-exporter
    environment:
      - HADOOP_HEAPSIZE_MAX=2048m
      - PIG_OPTS=-Dmapreduce.map.memory.mb=2048 -Dmapreduce.reduce.memory.mb=2048
    command: ["/entrypoint.sh"]
